#! /bin/sh


ruby src/create_documentation.rb

(cd latex; \
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=../build main.tex > ../build/main.out; \
biber ../build/main.bcf; \
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=../build main.tex >>xs ../build/main.out)

open build/main.pdf
