#! /bin/sh


ruby src/create_documentation.rb

(cd latex; \
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=../build mtc-ua.tex > ../build/mtc-ua.stdout; \
biber ../build/mtc-ua.bcf; \
pdflatex -synctex=1 -interaction=nonstopmode -output-directory=../build mtc-ua.tex >> ../build/mtc-ua.stdout)

# open build/mtc-ua.pdf
