#! /bin/sh

cp latex/diagrams/mtconnect-mapping/*.png ~/Dropbox/Apps/Overleaf/opc-mtconnect/diagrams/mtconnect-mapping
cp latex/diagrams/types/*.png ~/Dropbox/Apps/Overleaf/opc-mtconnect/diagrams/types

