(TeX-add-style-hook
 "types"
 (lambda ()
   (LaTeX-add-labels
    "fig:Components"
    "type:ChannelType"
    "table:ChannelType"
    "type:DescriptionType"
    "table:DescriptionType"
    "type:MTComponentType"
    "table:MTComponentType"
    "type:MTCompositionType"
    "table:MTCompositionType"
    "type:MTConfigurationType"
    "table:MTConfigurationType"
    "type:MTDeviceType"
    "table:MTDeviceType"
    "type:SensorConfigurationType"
    "table:SensorConfigurationType"
    "fig:Data Items"
    "type:AssetChangedType"
    "table:AssetChangedType"
    "type:AssetEventType"
    "table:AssetEventType"
    "type:AssetRemovedType"
    "table:AssetRemovedType"
    "type:MTDataItemType"
    "table:MTDataItemType"
    "type:MTEnumeratedEventType"
    "table:MTEnumeratedEventType"
    "type:MTFilterType"
    "table:MTFilterType"
    "type:MTMessageType"
    "table:MTMessageType"
    "type:MTNumericDataItemType"
    "table:MTNumericDataItemType"
    "type:MTNumericEventType"
    "table:MTNumericEventType"
    "type:MTSampleType"
    "table:MTSampleType"
    "type:MTStringEventType"
    "table:MTStringEventType"
    "type:MinimumDeltaFilterType"
    "table:MinimumDeltaFilterType"
    "type:PeriodFilterType"
    "table:PeriodFilterType"
    "fig:Conditions"
    "type:MTExclusiveLimitConditionType"
    "table:MTExclusiveLimitConditionType"
    "type:MTNonExclusiveConditionType"
    "table:MTNonExclusiveConditionType"
    "fig:Factories"
    "type:ComponentObjectFactory"
    "type:ComponentTypeFactory"
    "type:CompositionObjectFactory"
    "type:CompositionTypeFactory"
    "type:ConditionClassFactory"
    "type:ConditionObjectFactory"
    "type:DataItemObjectFactory"
    "type:DataItemTypeFactory"
    "type:DeviceObjectFactory"
    "type:FilterObjectFactory"
    "type:ObjectFactory"
    "type:SensorChannelObjectFactory"
    "type:SensorObjectFactory"
    "type:TypeFactory"
    "fig:MTConnect Device Profile"
    "type:Dynamic Type"
    "type:MTConnect XML"
    "type:MTRelationshipType"
    "type:Mixes  In"
    "type:Object Factory"
    "type:Type Factory"
    "type:bind"
    "type:constrains"
    "type:mixin"
    "type:use"))
 :latex)

