$ENV{'TZ'}='America/Los_Angeles';

add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
# add_cus_dep('ist', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
  if ( $silent ) {
    system "makeglossaries -q '$_[0]'";
  }
  else {
    system "makeglossaries '$_[0]'";
  };
}

